### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by haesleinhuepf** [German-BioImaging/RDM4mic#1]
Hi all, hi @sukunis ,

just a quick question regarding the license that was just added in https://github.com/German-BioImaging/RDM4mic/commit/1b1453e95818e017829bc77778c4a88f09a2f868 . Does it necessarily have to be this license? In NFDI4BioImage, we might want to rely on the materials published here and we're aiming for a CC-BY 4.0 license for sharing materials. We also might want to do paid courses, where only not-NC licenses would work. CC-BY-NC-SA is quite a constraint. Thus, I was wondering if there is a strong reason for this license.

Thanks!

Best,
Robert

**Comment by sukunis** [comment]
Hi @haesleinhuepf,

after the discussion at the last meeting, we decided to use the CC-BY 4.0 licence, unless someone wants to publish their material with a different licence, which is then marked in the material.

Best,
Susanne
